In [ ]:
import numpy as np

In [ ]:
l = [ 1, 2, 3, 4 ]

In [ ]:
arr1 = np.array(l)

In [ ]:
arr1

array([1, 2, 3, 4])

In [ ]:
np.zeros((3 , 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
list(range(0, 3))

[0, 1, 2]

In [ ]:
arr_range = np.arange(1, 11)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
type(arr_range)

numpy.ndarray

In [ ]:
np.random.random((3 , 3))

array([[0.20899023, 0.04844134, 0.42154863],
       [0.00313699, 0.5531135 , 0.55275627],
       [0.82217593, 0.64271798, 0.66696301]])

1- Crie um array com 4 linhas e 3 colunas com valores aleatórios

In [ ]:
np.random.random((4, 3))

array([[0.33872599, 0.74482308, 0.240005  ],
       [0.87403064, 0.95348588, 0.10147425],
       [0.69297846, 0.20112604, 0.85369311],
       [0.9004852 , 0.0203254 , 0.08501685]])

In [ ]:
np.random

<module 'numpy.random' from '/usr/local/lib/python3.10/dist-packages/numpy/random/__init__.py'>

2- Crie um arry com 5 colunas e 10 linhas iniciados com zero

In [ ]:
np.zeros((10 , 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Crie um array com valores inteiros 3 linhas e 5 colunas com valores com valores aleatórios

In [ ]:
np.random.randint(10, 30 , size=((3, 5)))

array([[29, 21, 24, 20, 11],
       [12, 11, 18, 22, 29],
       [14, 29, 10, 13, 17]])

criar um array que vá de 0 a 90, pulando de 4 em 4

In [ ]:
!pip install numpy
import numpy as np

In [ ]:
meu_array = np.arange(0, 91, 4)
meu_array

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88])

Crie array de 3 dimensões

In [ ]:
!pip install numpy
import numpy as np


In [ ]:
arr1_2d = np.array([[1, 2] , [3, 4]])
arr2_2d = np.array([[5, 6] , [7, 8]])
arr3_2d = np.array([[9, 2] , [3, 4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d])

In [ ]:
arr1_2d

array([[1, 2],
       [3, 4]])

In [ ]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [ ]:
arr1 = np.array([arr_3d, arr_3d])
arr1

array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[9, 2],
         [3, 4]]],


       [[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[9, 2],
         [3, 4]]]])

In [ ]:
arr1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8, 9, 2,
       3, 4])

In [ ]:
 arr = np.zeros((3, 4, 2))

In [ ]:
arr.shape

(3, 4, 2)

In [ ]:
arr.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [ ]:
arr_3d.reshape((4, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4]])

1. Reduza o array (5,7) a apenas uma dimensão

In [ ]:
a57 = np.random.random((5,7))
a57 = a57.flatten()
a57

array([0.02031978, 0.71579601, 0.97601905, 0.65169054, 0.04133196,
       0.09782021, 0.24036216, 0.54548142, 0.62255989, 0.34956891,
       0.98839953, 0.56389583, 0.918842  , 0.3348564 , 0.93448058,
       0.72211773, 0.02151136, 0.60298297, 0.02323369, 0.46915141,
       0.22138288, 0.87344308, 0.35718168, 0.48735148, 0.63476334,
       0.07165335, 0.57954929, 0.05146414, 0.0201429 , 0.97019155,
       0.86667237, 0.12749723, 0.40517704, 0.35916771, 0.56688041])

2. Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha desses jogos de bingo. os números da suas cartelas variam entre 1 e 30, e você terá 10 participantes. Cada cartela terá 12 números (4, 3).
Crie um array que represente esse jogo

In [ ]:
bingo = np.random.randint(1 , 31, size=(10, 4, 3))
bingo

array([[[22, 22, 29],
        [ 8, 23, 17],
        [15,  7, 13],
        [ 4,  7,  1]],

       [[19, 13, 22],
        [17, 17, 20],
        [29, 21, 18],
        [19, 13, 12]],

       [[ 6, 19, 11],
        [ 6, 15, 28],
        [17, 10,  8],
        [ 5, 14, 10]],

       [[ 4, 16,  5],
        [16, 22, 29],
        [26,  2, 12],
        [ 4, 13, 12]],

       [[ 4,  9,  5],
        [27, 21, 19],
        [19, 14, 20],
        [14, 25, 17]],

       [[22, 12,  5],
        [15, 19, 25],
        [ 1,  4, 28],
        [ 5,  4, 24]],

       [[ 3, 25, 15],
        [ 1,  2,  9],
        [23, 18, 13],
        [26, 25, 16]],

       [[ 3, 13, 29],
        [ 8, 22, 11],
        [ 2,  9, 21],
        [ 9, 13,  3]],

       [[14,  2, 17],
        [21,  9,  6],
        [ 4, 30,  5],
        [ 8, 30, 10]],

       [[28, 23, 28],
        [12, 29,  7],
        [15, 27,  6],
        [ 9, 17, 26]]])

3. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas

In [ ]:
bingo.reshape((5, 4, 6))


array([[[14,  8, 24,  4, 12,  5],
        [ 2,  5, 15, 15,  5, 27],
        [10, 29,  2, 13, 22,  9],
        [24, 25, 27, 16, 21, 11]],

       [[30, 15, 19,  2,  5, 18],
        [11, 19,  8, 19,  9, 23],
        [19,  2, 28, 25, 28, 21],
        [28, 28, 25, 28, 28,  1]],

       [[30,  9, 26,  6,  6, 22],
        [ 9,  2, 22,  2,  9, 14],
        [26, 18,  8,  5, 26, 12],
        [ 8,  2, 16, 26,  2, 16]],

       [[ 9, 28, 20, 27, 18, 10],
        [ 2,  6, 26,  4, 20,  3],
        [11,  7, 13,  6, 14, 14],
        [15, 24,  6, 21, 20,  8]],

       [[ 5,  1, 19, 10, 22,  7],
        [16,  9, 26,  4, 25, 22],
        [23, 22, 18, 22, 15, 20],
        [ 9, 20, 24, 28, 11, 10]]])

Tipo de dados em um numpy array

In [ ]:
np.array([5.4,6.7,2.1]).dtype

dtype('float64')

In [ ]:
np.array([5,6,2]).dtype

dtype('int64')

In [ ]:
np.array(["Hello", "womakerscode"]).dtype

dtype('<U12')

In [ ]:
x = np.array([3,4, 2.1])
x[1]

4.0

In [ ]:
np.array([True, 3, False])

array([1, 3, 0])

In [ ]:
x.astype(np.int32)

array([3, 4, 2], dtype=int32)

In [ ]:
vf = np.array([True, 3, False])
vf



array([1, 3, 0])

In [ ]:
vf.astype(np.float32)

array([1., 3., 0.], dtype=float32)

In [ ]:
x.astype(np.int32)

array([3, 4, 2], dtype=int32)

In [ ]:
import numpy as np


In [ ]:
arr = np.array([2, 4, 6, 7, 8])
arr[1]

4

In [ ]:
arr[0]

2

In [ ]:
!pip install numpy
import numpy as np

cartela_bingo = np.array([[16, 10,  3, 15],
                            [14, 23, 17, 27],
                            [ 6, 19,  3,  1],
                            [10,  4, 18, 19]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [ ]:
cartela_bingo[:,1].reshape((4,1))

array([[10],
       [23],
       [19],
       [ 4]])

In [ ]:
cartela_bingo[0]

array([16, 10,  3, 15])

In [ ]:
np.sort(cartela_bingo)

array([[ 3, 10, 15, 16],
       [14, 17, 23, 27],
       [ 1,  3,  6, 19],
       [ 4, 10, 18, 19]])

In [ ]:
np.sort(cartela_bingo, axis=0)

array([[ 6,  4,  3,  1],
       [10, 10,  3, 15],
       [14, 19, 17, 19],
       [16, 23, 18, 27]])

1.1 Explorando Ecossistemas:
Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas, considere a seguinte ordem de colunas:

ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie

Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies.
De qtd_especies selecione apenas as primeiras 3 quantidades e print
Print as 5 últimas quantidades de espécies
Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente

In [ ]:
especies = np.array([[747,  89,  33,   5],
                    [623, 123,  32,  13],
                    [501,  22,  49,   2],
                    [116, 101,  42,  10],
                    [297,  56,  69,  22],
                    [613,  64,  27,   7],
                    [295,  84,  29,  14],
                    [692, 105,  72,  16],
                    [229, 103,  35,   5],
                    [374, 124,  70,   1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [ ]:
qtd_especies = especies[:,1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [ ]:
print(qtd_especies[0:3])


[ 89 123  22]


In [ ]:
especies.shape

(10, 4)

In [ ]:
qtd_especies[5:]

array([ 64,  84, 105, 103, 124])

In [ ]:
especies[:,3]

array([ 5, 13,  2, 10, 22,  7, 14, 16,  5,  1])

In [ ]:
np.sort(especies[:,3])

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

In [ ]:
np.sort(especies[:,3])[::-1]

array([22, 16, 14, 13, 10,  7,  5,  5,  2,  1])

## 1.2 Ainda usando o Array de espécies marítimas.

Usando um index booleano crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22.

Usando fency index faça um array que contém apenas dados da espécie com ID 297

Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.

Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com "Profundo"

In [ ]:
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [ ]:
especies[:, 3] == 22

array([False, False, False, False,  True, False, False, False, False,
       False])

In [ ]:
maior_especies = especies[especies[:, 3] == 22]
maior_especies

array([[297,  56,  69,  22]])

In [ ]:
especies[:, 0] == 297

array([False, False, False, False,  True, False, False, False, False,
       False])

In [ ]:
mask_297 = especies[:, 0] == 297
mask_297

array([False, False, False, False,  True, False, False, False, False,
       False])

In [ ]:
especies[mask_297]

array([[297,  56,  69,  22]])

In [ ]:
np.where(especies[:, 1] == 105)

(array([7]),)

In [ ]:
especies[np.where(especies[:, 1] == 105)]

array([[692, 105,  72,  16]])

In [ ]:
especies[:, 2] > 60

array([False, False, False, False,  True, False, False,  True, False,
        True])

In [ ]:
np.where(especies[:, 2] > 60, "Profundo", especies[:, 2] )

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U21')

In [ ]:
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [ ]:
cartela_bingo1 = cartela_bingo[:3]
cartela_bingo1

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1]])

In [ ]:
cartela_bingo2 = cartela_bingo[-1:]
cartela_bingo2

array([[10,  4, 18, 19]])

In [ ]:
np.concatenate((cartela_bingo1,cartela_bingo2 ))

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [ ]:
cartela_bingo == np.concatenate((cartela_bingo1,cartela_bingo2 ))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
sala_espera = np.array([['5', '30', '1', 'Alice'],
                        ['6', '29', '1', 'Bob'],
                        ['7', '35', '3', 'Cristina'],
                        ['8', '34', '3', 'Luiz']])
sala_espera

array([['5', '30', '1', 'Alice'],
       ['6', '29', '1', 'Bob'],
       ['7', '35', '3', 'Cristina'],
       ['8', '34', '3', 'Luiz']], dtype='<U8')

In [ ]:
np.delete(sala_espera, 3, axis=0)

array([['5', '30', '1', 'Alice'],
       ['6', '29', '1', 'Bob'],
       ['7', '35', '3', 'Cristina']], dtype='<U8')

1.3 Ainda no conjunto 'especies'.
Adicione mais 2 espécies ao array: [[204, 10, 40, 12], [392, 11, 81, 11]]
Adicione mais uma coluna na no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0]

In [ ]:
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [ ]:
novas_especies = np.array([[204, 10, 40, 12], [392, 11, 81, 11]])
novas_especies

array([[204,  10,  40,  12],
       [392,  11,  81,  11]])

In [ ]:
np.concatenate((especies, novas_especies))

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

In [ ]:
!pip install numpy

import numpy as np


In [ ]:
np.concatenate((especies, np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1])), axis=1)


NameError: name 'especies' is not defined

In [ ]:
especies.shape


(10, 4)

In [ ]:
ver = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1]).reshape((10, 1))
ver

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [ ]:
np.concatenate((especies, ver), axis=1)

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1]])